# Generated by Django 4.2.5 on 2023-09-22 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255, verbose_name='Blug Title')),
                ('body', models.TextField(verbose_name='Blug Body')),
            ],
        ),
    ]
